version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: guitarist_postgres
    environment:
      POSTGRES_USER: guitarist
      POSTGRES_PASSWORD: guitarist
      POSTGRES_DB: guitarist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
